name: SolarChat
version: '${project.version}'
main: me.cyh2.solarchat.SolarChat
api-version: '1.19'
authors:
  - "cyh2"
  - "CosmicNebula"
  - "EternalStar"
  - "CosmicNebula旗下SolarMC"
website: "https://eternalstarmc.com:442/"
commands:
  GChatBan:
    permission: SolarChat.ChatBan
  ChatBan:
    permission: SolarChat.ChatBan
  show-ip:
    description: "显示您的IP"

permissions:
  SolarChat.ChatBan:
    description: "禁言权限"
    default: op

